### ISSUE TITLE
erreur 500 on list threads

### ISSUE THREAD

**Issue by esion** [CaliOpen/caliopen.api#3]
following error after authentication success : 

~~~
api_1 | 2015-12-19 15:56:03,801 DEBUG [caliopen.api.user.authentication][waitress] Authentication via Access Token                                                    [135/3253]
api_1 | 2015-12-19 15:56:03,803 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (1): localhost
api_1 | 2015-12-19 15:56:03,804 WARNI [elasticsearch][waitress] GET http://localhost:9200/715814d1-097e-47d5-b628-e20d2b1c0bfa/threads/_search [status:N/A request:0.001s]
api_1 | Traceback (most recent call last):
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
api_1 |     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
api_1 |     _pool=self, _stacktrace=stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 223, in increment
api_1 |     raise six.reraise(type(error), error, _stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
api_1 |     body=body, headers=headers)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
api_1 |     conn.request(method, url, **httplib_request_kw)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1001, in request
api_1 |     self._send_request(method, url, body, headers)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
api_1 |     self.endheaders(body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
api_1 |     self._send_output(message_body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
api_1 |     self.send(msg)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 812, in send
api_1 |     self.connect()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 154, in connect
api_1 |     conn = self._new_conn()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 133, in _new_conn
api_1 |     (self.host, self.port), self.timeout, **extra_kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 87, in create_connection
api_1 |     raise err
api_1 | ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
api_1 | 2015-12-19 15:56:03,804 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (2): localhost
api_1 | 2015-12-19 15:56:03,805 WARNI [elasticsearch][waitress] GET http://localhost:9200/715814d1-097e-47d5-b628-e20d2b1c0bfa/threads/_search [status:N/A request:0.001s]
api_1 | Traceback (most recent call last):
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
api_1 |     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
api_1 |     _pool=self, _stacktrace=stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 223, in increment
api_1 |     raise six.reraise(type(error), error, _stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
api_1 |     body=body, headers=headers)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
api_1 |     conn.request(method, url, **httplib_request_kw)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1001, in request
api_1 |     self._send_request(method, url, body, headers)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
api_1 |     self.endheaders(body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
api_1 |     self._send_output(message_body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
api_1 |     self.send(msg)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 812, in send
api_1 |     self.connect()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 154, in connect
api_1 |     conn = self._new_conn()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 133, in _new_conn
api_1 |     (self.host, self.port), self.timeout, **extra_kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 87, in create_connection
api_1 |     raise err
api_1 | ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
api_1 | 2015-12-19 15:56:03,805 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (3): localhost
api_1 | 2015-12-19 15:56:03,806 WARNI [elasticsearch][waitress] GET http://localhost:9200/715814d1-097e-47d5-b628-e20d2b1c0bfa/threads/_search [status:N/A request:0.001s]
api_1 | Traceback (most recent call last):
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
api_1 |     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
api_1 |     _pool=self, _stacktrace=stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 223, in increment
api_1 |     raise six.reraise(type(error), error, _stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
api_1 |     body=body, headers=headers)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
api_1 |     conn.request(method, url, **httplib_request_kw)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1001, in request
api_1 |     self._send_request(method, url, body, headers)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
api_1 |     self.endheaders(body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
api_1 |     self._send_output(message_body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
api_1 |     self.send(msg)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 812, in send
api_1 |     self.connect()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 154, in connect
api_1 |     conn = self._new_conn()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 133, in _new_conn
api_1 |     (self.host, self.port), self.timeout, **extra_kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 87, in create_connection
api_1 |     raise err
api_1 | ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
api_1 | 2015-12-19 15:56:03,807 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (4): localhost
api_1 | 2015-12-19 15:56:03,808 WARNI [elasticsearch][waitress] GET http://localhost:9200/715814d1-097e-47d5-b628-e20d2b1c0bfa/threads/_search [status:N/A request:0.002s]
api_1 | Traceback (most recent call last):
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
api_1 |     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
api_1 |     _pool=self, _stacktrace=stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 223, in increment
api_1 |     raise six.reraise(type(error), error, _stacktrace)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
api_1 |     body=body, headers=headers)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
api_1 |     conn.request(method, url, **httplib_request_kw)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1001, in request
api_1 |     self._send_request(method, url, body, headers)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
api_1 |     self.endheaders(body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
api_1 |     self._send_output(message_body)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
api_1 |     self.send(msg)
api_1 |   File "/usr/lib/python2.7/httplib.py", line 812, in send
api_1 |     self.connect()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 154, in connect
api_1 |     conn = self._new_conn()
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 133, in _new_conn
api_1 |     (self.host, self.port), self.timeout, **extra_kw)
api_1 |   File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 87, in create_connection
api_1 |     raise err
api_1 | ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
api_1 | 2015-12-19 15:56:03,810 ERROR [waitress][waitress] Exception when serving /api/v1/threads
api_1 | Traceback (most recent call last):
api_1 |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.10-py2.7.egg/waitress/channel.py", line 336, in service
api_1 |     task.service()
api_1 |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.10-py2.7.egg/waitress/task.py", line 169, in service
api_1 |     self.execute()
api_1 |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.10-py2.7.egg/waitress/task.py", line 388, in execute
api_1 |     app_iter = self.channel.server.application(env, start_response)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 242, in __call__
api_1 |     response = self.invoke_subrequest(request, use_tweens=True)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 217, in invoke_subrequest
api_1 |     response = handle_request(request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 46, in excview_tween
api_1 |     response = view_callable(exc, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 385, in viewresult_to_response
api_1 |     result = view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 21, in excview_tween
api_1 |     response = handler(request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 163, in handle_request
api_1 |     response = view_callable(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 596, in __call__
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 329, in attr_view
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 305, in predicate_wrapper
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 245, in _secured_view
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 355, in rendered_view
api_1 |     result = view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 501, in _requestonly_view
api_1 |     response = view(request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
api_1 |     response = view_()
api_1 |   File "/usr/local/lib/python2.7/dist-packages/caliopen/api/message/thread.py", line 26, in collection_get
api_1 |     offset=self.get_offset())
api_1 |   File "/usr/local/lib/python2.7/dist-packages/caliopen/base/message/core/thread.py", line 226, in main_view
api_1 |     offset=offset)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/caliopen/base/core/mixin.py", line 123, in find_index
api_1 |     offset=offset)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/caliopen/base/store/model.py", line 190, in all
api_1 |     res = s.execute()
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/search.py", line 573, in execute
api_1 |     **self._params
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
api_1 |     return func(*args, params=params, **kwargs)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 530, in search
api_1 |     doc_type, '_search'), params=params, body=body)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
api_1 |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
api_1 |     raise ConnectionError('N/A', str(e), e)
api_1 | ConnectionError: ConnectionError(('Connection aborted.', error(111, 'Connection refused'))) caused by: ProtocolError(('Connection aborted.', error(111, 'Connection refu
sed')))
~~~

**Comment by esion** [comment]
I didn't read the error, may be it is also related to a docker link since it should not be an URL like 
`http://localhost:9200/` but `http://es.dev.caliopen.org:9200`

**Comment by gdchamal** [comment]
yes something try to connect to elasticsearch using localhost instead of configured value.

I start tracking this issue but can't find any localhost reference. I guess use of ES client /w any configuration default to localhost, have to find where it is

**Comment by gdchamal** [comment]
Well apparently configuration key renaming that is not done in ES base class:

(venv)tao~/dev/caliopen/base(remove-cqlengine|✚1) % git diff
diff --git a/caliopen/base/store/model.py b/caliopen/base/store/model.py
index d85996d..96ff116 100644
--- a/caliopen/base/store/model.py
+++ b/caliopen/base/store/model.py
@@ -57,7 +57,7 @@ class BaseIndexDocument(object):
 
     columns = []
     doc_type = None
-    __url__ = Configuration('global').get('elasticsearch.url')
+    __url__ = Configuration('global').get('index_server.url')
 
     def __init__(self, data):
         """Create a BaseIndexDocument instance from a dict.

should fix this issue.

**Comment by esion** [comment]
As we spoke, I've successfully used docker volume to patch this code unfortunately it does not change anything.

**Comment by gdchamal** [comment]
will try to reproduce and check if there is no other misconfiguration

**Comment by esion** [comment]
fixes in base, base.message ... fix this problem
